
language: php

php:
  - 7.3
  - 7.4

script:
  - mkdir -p build/logs
  - composer install
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry  php vendor/bin/coveralls
  - travis_retry php vendor/bin/coveralls -v
